apiVersion: v1
kind: Pod
metadata:
  name: affinity-demo
  labels:
    app: affinity-demo
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values: ["linux"]
              - key: disktype
                operator: In
                values: ["ssd", "nvme"]
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 80
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: ["practice-worker"]
        - weight: 20
          preference:
            matchExpressions:
              - key: zone
                operator: In
                values: ["ap-south-1a"]
  containers:
    - name: app
      image: nginx:1.27-alpine
      resources:
        requests: { cpu: "50m", memory: "32Mi" }
        limits: { cpu: "100m", memory: "64Mi" }