apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-alpha-quota
  namespace: team-alpha
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "10"
    services: "5"
    services.loadbalancers: "1"
    persistentvolumeclaims: "4"
    requests.storage: 5Gi
    count/jobs.batch: "5"